---
apiVersion: v1
kind: Namespace
metadata:
  name: kvcd-system
  labels:
    application: kvcd-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kvcd-account
  namespace: kvcd-system
  labels:
    application: kvcd-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kvcd-role-cluster
  labels:
    application: kvcd-operator
rules:
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [kvcd.lrivallain.dev]
    resources: [vcdvapps]
    verbs: [list, watch, patch]
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kvcd-rolebinding-cluster
  labels:
    application: kvcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kvcd-role-cluster
subjects:
  - kind: ServiceAccount
    name: kvcd-account
    namespace: kvcd-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvcd-operator
  namespace: kvcd-system
  labels:
    application: kvcd-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kvcd-operator
  template:
    metadata:
      labels:
        application: kvcd-operator
    spec:
      serviceAccountName: kvcd-account
      containers:
      - name: kvcd-operator
        image: lrivallain/kvcd:latest
        envFrom:
        - configMapRef:
            name: kvcd-config
